### ISSUE TITLE
raw should be renamed

### ISSUE THREAD

**Issue by pietdevaere** [mami-project/observatory-upload#8]
`raw` should be renamed to something more clear, like `plain` or `txt` or something.

**Comment by FMNSSun** [comment]
Actually maybe removing it completely might even be smarter.

**Comment by FMNSSun** [comment]
Yeah, remove the `raw` versions. They're bound to cause non-matching hashes due to newline conversions and are probably prone to encoding issues which will also cause non-matching hashes. Not that non-matching hashes are inherently a problem for the upload service it's just that it is confusing for people using the service.

**Comment by FMNSSun** [comment]
(Marked deprecated).
